### ISSUE TITLE
NFC reader unlocking fail

### ISSUE THREAD

**Issue by kimmoal** [BiathlonHelsinki/kiosk#2]
https://github.com/BiathlonHelsinki/kiosk/blob/master/main.js#L229
Fails with:
```
name is Kimmo
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'req' of undefined
    at Object.exports.lock (/home/pi/kiosk/node_modules/lockfile/lockfile.js:138:19)
    at safe_to_write (/home/pi/kiosk/main.js:229:13)
...
```
Per lockfile documentation:
```
lockFile.lock(path, [opts], cb)
Acquire a file lock on the specified path
```
Needs callback to fail nicely!

**Comment by cenotaph** [comment]
Should be fixed in this commit. I decided not to go with a lockfile, figured the constant writing to the SD card would just wear it out and it seems to be working without. Forgot to remove this line; can you git pull on the kiosk and if it works now, close this issue?

**Comment by kimmoal** [comment]
It does not seem to work, the card is not found in the database although the writing seems to go through okay (previously it got stuck in the writing phase)

**Comment by kimmoal** [comment]
Sent you the logs :1st_place_medal:

**Comment by kimmoal** [comment]
Fixed!
